language: node_js
node_js:
  - "5.1"
  - "4.2"

install:
  - ./bin/install
  - npm i
  - npm i sidekick

script:
  - npm test
  - sidekick -v
  - sidekick run --travis

notifications:
  slack: we-are-sidekick:GeIT5wtuKMLImpFXYHWzIGzI
